// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkR0bszzj9NfjEruQYuBMHx2Mqf4i6sps',
    appId: '1:696028434424:web:08709dc4d5bb6a0becd00d',
    messagingSenderId: '696028434424',
    projectId: 'ai-fitness-tracker-ec948',
    authDomain: 'ai-fitness-tracker-ec948.firebaseapp.com',
    storageBucket: 'ai-fitness-tracker-ec948.firebasestorage.app',
    measurementId: 'G-ZPNFZ23VH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuX2mHKjdDhgICwcPjy1sipvPI3WcsX40',
    appId: '1:696028434424:android:f2d7bd97367725aeecd00d',
    messagingSenderId: '696028434424',
    projectId: 'ai-fitness-tracker-ec948',
    storageBucket: 'ai-fitness-tracker-ec948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHL79PmanGsOTev1ejgqAI8OZOZMseNbs',
    appId: '1:696028434424:ios:dea557c2e6a250ddecd00d',
    messagingSenderId: '696028434424',
    projectId: 'ai-fitness-tracker-ec948',
    storageBucket: 'ai-fitness-tracker-ec948.firebasestorage.app',
    androidClientId: '696028434424-ff18hb70vk2r150irbcdtjgf7f5v5hll.apps.googleusercontent.com',
    iosClientId: '696028434424-0cikk0gi94raloevlun40tn5irs4umj9.apps.googleusercontent.com',
    iosBundleId: 'com.ahmad.aifitnesstracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHL79PmanGsOTev1ejgqAI8OZOZMseNbs',
    appId: '1:696028434424:ios:5204af8e8470b3c4ecd00d',
    messagingSenderId: '696028434424',
    projectId: 'ai-fitness-tracker-ec948',
    storageBucket: 'ai-fitness-tracker-ec948.firebasestorage.app',
    androidClientId: '696028434424-ff18hb70vk2r150irbcdtjgf7f5v5hll.apps.googleusercontent.com',
    iosClientId: '696028434424-5jt6nmdvpo8edervsb0micll3h98ka07.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiFitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkR0bszzj9NfjEruQYuBMHx2Mqf4i6sps',
    appId: '1:696028434424:web:cd925db41e032298ecd00d',
    messagingSenderId: '696028434424',
    projectId: 'ai-fitness-tracker-ec948',
    authDomain: 'ai-fitness-tracker-ec948.firebaseapp.com',
    storageBucket: 'ai-fitness-tracker-ec948.firebasestorage.app',
    measurementId: 'G-NZJSD2N56C',
  );
}
